spring:
  oauth2:
    client:
      clientId: 364496581292284
      clientSecret: 97300ad6afec5358bee195ff896a0e6e
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me